export const usersList = [
  {
    id: 2833,
    name: 'Kathline Villanveva',
    email: 'Kathline.Villanveva20040@test.com',
    gender: 'male',
    status: 'inactive',
  },
  {
    id: 2842,
    name: 'Turner59',
    email: 'iswam+voluptatibus@example.com',
    gender: 'female',
    status: 'active',
  },
  {
    id: 2843,
    name: '{{$randomlastName}}',
    email: 'iswam+eaque@example.com',
    gender: 'female',
    status: 'inactive',
  },
  {
    id: 2844,
    name: 'Abshire',
    email: 'iswam+molestiae@example.com',
    gender: 'male',
    status: 'inactive',
  },
  {
    id: 2847,
    name: 'Merlin',
    email: 'iswam+rerum@example.com',
    gender: 'female',
    status: 'active',
  },
  {
    id: 2850,
    name: 'Glaucio11 Silveira',
    email: 'glaucio1@glaucio11.com',
    gender: 'male',
    status: 'active',
  },
  {
    id: 2851,
    name: 'Glaucio12 Silveira',
    email: 'glaucio1@glaucio12.com',
    gender: 'male',
    status: 'active',
  },
  {
    id: 2852,
    name: 'Glaucio13 Silveira',
    email: 'glaucio1@glaucio13.com',
    gender: 'male',
    status: 'active',
  },
  {
    id: 2853,
    name: 'Glaucio14 Silveira',
    email: 'glaucio1@glaucio14.com',
    gender: 'male',
    status: 'active',
  },
  {
    id: 1846,
    name: 'Sandeep',
    email: 'FnjdDxEUnw@gmail.com',
    gender: 'male',
    status: 'active',
  },
  {
    id: 1847,
    name: 'sdfasf',
    email: 'ad@dsf.hbd',
    gender: 'male',
    status: 'inactive',
  },
  {
    id: 1864,
    name: 'yas',
    email: 'yas@gmail.com',
    gender: 'male',
    status: 'active',
  },
  {
    id: 1865,
    name: 'Tenali Ramakrishna',
    email: 'tenalitenali.ramakrishna@15ce.com',
    gender: 'male',
    status: 'active',
  },
  {
    id: 1866,
    name: 'preethi1',
    email: 'preethi@ibhubs.co',
    gender: 'unknown',
    status: 'active',
  },
  {
    id: 1867,
    name: 'Sandeep',
    email: 'HhcKSIlYMh@gmail.com',
    gender: 'male',
    status: 'forzen',
  },
  {
    id: 1868,
    name: 'Sandeep',
    email: 'aSeHuIpEKI@gmail.com',
    gender: 'male',
    status: 'active',
  },
  {
    id: 1869,
    name: 'Sandeep',
    email: 'PcAjmqGlzZ@gmail.com',
    gender: 'unknown',
    status: 'active',
  },
  {
    id: 1923,
    name: 'Sandeep',
    email: 'JImqSLUafA@gmail.com',
    gender: 'male',
    status: 'active',
  },
  {
    id: 2841,
    name: 'Skaskiv VolodymyrGGGGGGG',
    email: 'iswam@ukr.net',
    gender: 'male',
    status: 'frozen',
  },
  {
    id: 1942,
    name: 'name73441',
    email: 'mail73441@mail.com',
    gender: 'male',
    status: 'onhold',
  },
];
